mod_id=xbob
mod_name=Crosshair Bobbing
mod_version=2.0
mod_author=Krash220
mod_package=krash220.xbob
mod_entrypoint=krash220.xbob.MainMod
mod_url=https://github.com/Krash220/CrosshairBobbingMod
mod_license=MIT
